<a href="https://colab.research.google.com/github/C0C045/Python-challenge/blob/main/ExercisesNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise 1

In [ ]:
import numpy as np


A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


### Exercise 2

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array,axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


###Exercise 3

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


###Exercise 4

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


###Exercise 5

In [ ]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


###Exercise 6

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(np.allclose(A,B))

True


###Exercise 7

In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A == B)

[False False  True]
[False False  True]


###Exercise 8

In [ ]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(A>B)

[ True False False False]


###Exercise 9

In [ ]:
print(np.zeros((4,4), int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#Exercise 10

In [ ]:
print(np.full((10,10), 255, float)) #O con np.ones((10,10), float)*255

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


###Exercise 11

In [ ]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


###Exercise 12

In [ ]:
print(np.arange(10,100).reshape(9,10))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


###Exercise 13

In [ ]:
print(np.eye(6,dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


###Exercise 14

In [ ]:
print(np.random.rand(30))

[0.66316841 0.21011042 0.84917522 0.39928012 0.22109328 0.99522292
 0.34696261 0.45161447 0.41862908 0.61719573 0.86118274 0.64854144
 0.11252138 0.37943791 0.95586328 0.33725561 0.05468636 0.4982989
 0.53801594 0.12831282 0.21097033 0.92075951 0.33598384 0.46948043
 0.15648178 0.61436647 0.30872606 0.90265434 0.20540045 0.55762028]


In [ ]:
square = np.full((3,3)," ", dtype=str)
mark = " "
print("¡El primer jugador es la X y el segundo la O!")
print("Forma de escribir las posiciones: Fila Columna. Ej: 1 2")

def printMatriz():
  for i in range(3):
    print("|",*square[i],"|")

printMatriz()

def checkTriqui():
  for i in range(3):
    if np.all(square[i]=="X") or np.all(square[:,i]=="X") or np.all(square.diagonal()=="X") or np.all(np.flip(square,1).diagonal()=="X"):
      print("Gano la X")
      return True
    elif np.all(square[i]=="O") or np.all(square[:,i]=="O") or np.all(square.diagonal()=="O") or np.all(np.flip(square,1).diagonal()=="O"):
      print("Gano la O")
      return True

for i in range(np.size(square)):
  if checkTriqui():
    break
  if i % 2 == 0:
    mark = "X"
  else:
    mark = "O"
  n = input("En qué posición va a poner su marca: \n")
  pos = np.array(n.split()).astype(int)-1
  if (0<=pos[0]<=2 and 0<=pos[1]<=2 and square[pos[0]][pos[1]]==" "):
    square[pos[0]][pos[1]] = mark
    printMatriz()
  else:
    while (pos[0]>2 or pos[1]>2 or pos[0]<0 or pos[1]>2 or square[pos[0]][pos[1]] != " "):
      print("La posición ingresada ya esta ocupada o es invalida, intente nuevamente")
      n = input("En qué posición va a poner su marca: \n")
      pos = np.array(n.split()).astype(int)-1
    square[pos[0]][pos[1]] = mark
    printMatriz()

print("Juego terminado")


¡El primer jugador es la X y el segundo la O!
Forma de escribir las posiciones: Fila Columna. Ej: 1 2
|       |
|       |
|       |
En qué posición va a poner su marca: 
1 1
| X     |
|       |
|       |
En qué posición va a poner su marca: 
1 2
| X O   |
|       |
|       |
En qué posición va a poner su marca: 
2 2
| X O   |
|   X   |
|       |
En qué posición va a poner su marca: 
1 4
La posición ingresada ya esta ocupada o es invalida, intente nuevamente
En qué posición va a poner su marca: 
1 1
La posición ingresada ya esta ocupada o es invalida, intente nuevamente
En qué posición va a poner su marca: 
2 3
| X O   |
|   X O |
|       |
En qué posición va a poner su marca: 
3 3
| X O   |
|   X O |
|     X |
Gano la X
Juego terminado


###Pruba flip() y diagonal()

In [ ]:
hl = np.arange(11,36).reshape(5,5)
print(hl)
h = np.flip(hl,1)
print(h.diagonal())

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[15 19 23 27 31]


In [ ]:
x = 5
y = x
z = y
if (x and y and z)==5:
  print("Funciona")

Funciona
